In [2]:
import os
os.listdir()

['description.txt',
 'Movie Genre.ipynb',
 'test_data.txt',
 'test_data_solution.txt',
 'train_data.txt']

1.Read data Or Extract the data

In [3]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
data=pd.read_csv("description.txt")
data

                                         Train data:
0             ID ::: TITLE ::: GENRE ::: DESCRIPTION
1             ID ::: TITLE ::: GENRE ::: DESCRIPTION
2             ID ::: TITLE ::: GENRE ::: DESCRIPTION
3             ID ::: TITLE ::: GENRE ::: DESCRIPTION
4                                         Test data:
5                       ID ::: TITLE ::: DESCRIPTION
6                       ID ::: TITLE ::: DESCRIPTION
7                       ID ::: TITLE ::: DESCRIPTION
8                       ID ::: TITLE ::: DESCRIPTION
9                                            Source:
10  ftp://ftp.fu-berlin.de/pub/misc/movies/database/

2.Create a Function to read data which is splited by ":::"

In [4]:
def process_data(file_path):
    with open(file_path,'r',encoding='utf-8') as f:
        data=f.readlines()
    data=[line.strip().split(" ::: ") for line in data]

    return data

train_data=process_data("train_data.txt")
train_df=pd.DataFrame(train_data,columns=['ID','Title','Genre','Description'])

test_data=process_data("test_data.txt")
test_df=pd.DataFrame(test_data,columns=['ID','Title','Description'])

test_data_solution=process_data("test_data_solution.txt")
test_solution_df=pd.DataFrame(test_data_solution,columns=['ID','Title','Genre','Description'])

print("Train Data:")
train_df

Train Data:

,ID,Title,Genre,Description
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his doc...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous re...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fiel...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends meet...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-rec...
...,...,...,...,...
54209,54210,"""Bonino"" (1953)",comedy,This short-lived NBC live sitcom centered on B...
54210,54211,Dead Girls Don't Cry (????),horror,The NEXT Generation of EXPLOITATION. The siste...
54211,54212,Ronald Goedemondt: Ze bestaan echt (2008),documentary,"Ze bestaan echt, is a stand-up comedy about gr..."
54212,54213,Make Your Own Bed (1944),comedy,Walter and Vivian live in the country and have...
54213,54214,Nature's Fury: Storm of the Century (2006),history,"On Labor Day Weekend, 1935, the most intense h..."

In [5]:
print("Test Data:")
test_df

Test Data:

,ID,Title,Description
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apart..."
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty chi..."
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family o...
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with his..."
4,5,Er nu zhai (1955),Before he was known internationally as a marti...
...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)","Covering multiple genres, Tales of Light & Dar..."
54196,54197,Der letzte Mohikaner (1965),As Alice and Cora Munro attempt to find their ...
54197,54198,Oliver Twink (2007),"A movie 169 years in the making. Oliver Twist,..."
54198,54199,Slipstream (1973),"Popular, but mysterious rock D.J Mike Mallard ..."
54199,54200,Curitiba Zero Grau (2010),"Curitiba is a city in movement, with rhythms a..."

In [6]:
print("Test Dat solution:")
test_solution_df

Test Dat solution:

,ID,Title,Genre,Description
0,1,Edgar's Lunch (1998),thriller,"L.R. Brane loves his life - his car, his apart..."
1,2,La guerra de papá (1977),comedy,"Spain, March 1964: Quico is a very naughty chi..."
2,3,Off the Beaten Track (2010),documentary,One year in the life of Albin and his family o...
3,4,Meu Amigo Hindu (2015),drama,"His father has died, he hasn't spoken with his..."
4,5,Er nu zhai (1955),drama,Before he was known internationally as a marti...
...,...,...,...,...
54195,54196,"""Tales of Light & Dark"" (2013)",horror,"Covering multiple genres, Tales of Light & Dar..."
54196,54197,Der letzte Mohikaner (1965),western,As Alice and Cora Munro attempt to find their ...
54197,54198,Oliver Twink (2007),adult,"A movie 169 years in the making. Oliver Twist,..."
54198,54199,Slipstream (1973),drama,"Popular, but mysterious rock D.J Mike Mallard ..."
54199,54200,Curitiba Zero Grau (2010),drama,"Curitiba is a city in movement, with rhythms a..."

3.Feature Extraction like TF-IDF

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=10000)
x_train_tfidf=vectorizer.fit_transform(train_df["Description"])
x_test_tfidf=vectorizer.transform(test_df["Description"])
print(f"Training data shape: {x_train_tfidf.shape}")
print(f"Testing data shape: {x_test_tfidf.shape}")

Training data shape: (54214, 10000)
Testing data shape: (54200, 10000)

4.Encoding the Target Labels

In [8]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y_train=label.fit_transform(train_df['Genre'])
print(f"Genre in trainig data: {label.classes_}")

Genre in trainig data: ['action' 'adult' 'adventure' 'animation' 'biography' 'comedy' 'crime'
 'documentary' 'drama' 'family' 'fantasy' 'game-show' 'history' 'horror'
 'music' 'musical' 'mystery' 'news' 'reality-tv' 'romance' 'sci-fi'
 'short' 'sport' 'talk-show' 'thriller' 'war' 'western']

5.Model building using Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression
LR_model=LogisticRegression(max_iter=200)
LR_model.fit(x_train_tfidf,y_train)
y_predict=LR_model.predict(x_test_tfidf)
predicted_genres=label.inverse_transform(y_predict)
test_df['Predicted_Genre']=predicted_genres
test_df[['Title','Predicted_Genre']]

                                Title Predicted_Genre
0                Edgar's Lunch (1998)           drama
1            La guerra de papá (1977)           drama
2         Off the Beaten Track (2010)     documentary
3              Meu Amigo Hindu (2015)           drama
4                   Er nu zhai (1955)           drama
...                               ...             ...
54195  "Tales of Light & Dark" (2013)           drama
54196     Der letzte Mohikaner (1965)           drama
54197             Oliver Twink (2007)          comedy
54198               Slipstream (1973)           drama
54199       Curitiba Zero Grau (2010)     documentary

[54200 rows x 2 columns]

In [10]:
merged_df=pd.merge(test_solution_df[['ID','Genre']],test_df[['ID','Predicted_Genre']],on='ID')
merged_df

          ID        Genre Predicted_Genre
0          1     thriller           drama
1          2       comedy           drama
2          3  documentary     documentary
3          4        drama           drama
4          5        drama           drama
...      ...          ...             ...
54195  54196       horror           drama
54196  54197      western           drama
54197  54198        adult          comedy
54198  54199        drama           drama
54199  54200        drama     documentary

[54200 rows x 3 columns]

6.Model Evaluation using Logistic Regression

In [11]:
from sklearn.metrics import accuracy_score,classification_report

accuracy=accuracy_score(merged_df['Genre'],merged_df['Predicted_Genre'])
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(merged_df['Genre'],merged_df['Predicted_Genre']))

Accuracy: 0.5946

Classification Report:
              precision    recall  f1-score   support

      action       0.51      0.30      0.37      1314
       adult       0.65      0.25      0.36       590
   adventure       0.68      0.16      0.26       775
   animation       0.61      0.04      0.08       498
   biography       0.00      0.00      0.00       264
      comedy       0.54      0.60      0.57      7446
       crime       0.41      0.03      0.06       505
 documentary       0.68      0.87      0.76     13096
       drama       0.55      0.78      0.65     13612
      family       0.49      0.08      0.14       783
     fantasy       0.61      0.03      0.06       322
   game-show       0.91      0.50      0.64       193
     history       0.00      0.00      0.00       243
      horror       0.66      0.57      0.61      2204
       music       0.68      0.46      0.55       731
     musical       0.50      0.02      0.03       276
     mystery       0.25      0.00      0.01       318
        news       0.67      0.06      0.10       181
  reality-tv       0.50      0.21      0.30       883
     romance       0.43      0.02      0.05       672
      sci-fi       0.60      0.26      0.36       646
       short       0.48      0.34      0.40      5072
       sport       0.72      0.28      0.41       431
   talk-show       0.60      0.19      0.29       391
    thriller       0.41      0.12      0.19      1590
         war       1.00      0.01      0.02       132
     western       0.91      0.73      0.81      1032

    accuracy                           0.59     54200
   macro avg       0.56      0.26      0.30     54200
weighted avg       0.58      0.59      0.55     54200